import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import Navbar from '@/components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-green-400 to-blue-400'>
        <section className='grid-cols-12 gap-6 px-5 lg:px-48 lg:grid my-14 sm:px-20 md:px-32'>
          <aside className='col-span-3 p-4 mb-4 bg-white rounded-2xl'>
            <Sidebar></Sidebar>
          </aside>
          <section className='flex flex-col col-span-9 p-4 bg-white rounded-2xl'>
            <Navbar></Navbar>
            {children}
          </section>
        </section>
      </body>
    </html>
  )
}
